TYPE
	Counter_Type : STRUCT
		Input	:BOOL;	
		Status	:UINT;	
		StartTimer	:UINT;	
		OnDelay	:UINT;	
		OffDelay	:UINT;	
		Counter	:UINT;	
		TrailCounter	:UINT;	
		OldCounter	:UINT;	
		OldTrailCounter	:UINT;	
		MuteTime	:UINT;	
		Output	:BOOL;	
	END_STRUCT;
			FoldIOCounter_Type : STRUCT
		Input	:BOOL;	
		Status	:UINT;	
		StartTimer	:UINT;	
		OnDelay	:UINT;	
		OffDelay	:UINT;	
		Counter	:UINT;	
		EdgeCounter	:UINT;	
		TrailCounter	:UINT;	
		EdgeFlank	:BOOL;	
		TrailFlank	:BOOL;	
		OldCounter	:UINT;	
		OldEdgeCounter	:UINT;	
		OldTrailCounter	:UINT;	
		Output	:BOOL;	
	END_STRUCT;
			FoldIO_Type : STRUCT
		Name	:STRING[21];	
		State	:UINT;	
		StartDelayTime	:UINT;	
		Timer	:UINT;	
		DoRunTimes	:UINT;	
		HasRunTimes	:UINT;	
		OnTime	:UINT;	
		Output	:BOOL;	
	END_STRUCT;
			FoldItem_Type : STRUCT
		Category	:UINT;	
		FoldProgram	:UINT;	
		Article	:UINT;	
		ClientNumber	:UINT;	
	END_STRUCT;
			FoldLogVariable_Type : STRUCT
		Index	:UINT;	
		ProcessStage	:UINT;	
		CurTimer	:UINT;	
		StageName	:STRING[21];	
		Text	:STRING[21];	
		Value	:UINT;	
		StatusCode	:UINT;	
		TimeStamp	:DATE_AND_TIME;	
	END_STRUCT;
			FoldProcessControl_Type : STRUCT
		Id	:UINT;	
		Name	:STRING[21];	
		State	:UINT;	
		ErrorCode	:UINT;	
		Run	:BOOL;	
		Ready	:BOOL;	
		ResetAlarm	:BOOL;	
		NextItemFlag	:UINT;	
		StageComplete	:BOOL;	
		ByPass	:BOOL;	
		Simulate	:BOOL;	
		Service	:BOOL;	
		DebugLogFlag	:BOOL;	
	END_STRUCT;
			FoldManager_Type : STRUCT
		FoldProcessesControl	:ARRAY[0..20] OF FoldProcessControl_Type;	
	END_STRUCT;
			FoldPositioningMotor_Type : STRUCT
		State	:UINT;	
		Enable	:BOOL;	
		Flag	:UINT;	
		Simulate	:BOOL;	
		HomeMaxMiscount	:UINT;	
		HomePosition	:BOOL;	
		OutPosition	:BOOL;	
		CurrentPosition	:DINT;	
		TargetPosition	:DINT;	
		TargetRange	:INT;	
		Reset	:BOOL;	
		MotorRun	:BOOL;	
		MotorDirection	:BOOL;	
		MotorLowSpeed	:UINT;	
		MotorHighSpeed	:UINT;	
		MotorSpeed	:UINT;	
		BrakeDistance	:UINT;	
		MaxRunTime	:UINT;	
		MaxRunTimer	:UINT;	
		ErrorCode	:UINT;	
		Name	:STRING[11];	
	END_STRUCT;
			FoldSpeedMotor_Type : STRUCT
		State	:UINT;	
		Enable	:BOOL;	
		Flag	:UINT;	
		Simulate	:BOOL;	
		TargetPosition	:UINT;	
		HomePosition	:BOOL;	
		OutPosition	:BOOL;	
		HomeBreakPosition	:BOOL;	
		OutBreakPosition	:BOOL;	
		InFastZone	:BOOL;	
		Reset	:BOOL;	
		MotorRun	:BOOL;	
		MotorDirection	:BOOL;	
		MotorLowSpeed	:UINT;	
		MotorHighSpeed	:UINT;	
		MotorPressSpeed	:UINT;	
		MotorSpeed	:UINT;	
		MotorPressOutTime	:UINT;	
		MotorPressOutTimer	:UINT;	
		MaxRunTime	:UINT;	
		MaxRunTimer	:UINT;	
		ErrorCode	:UINT;	
		Name	:STRING[11];	
	END_STRUCT;
			FoldSpeedPositionMotor_Type : STRUCT
		State	:UINT;	
		Enable	:BOOL;	
		Flag	:UINT;	
		Simulate	:BOOL;	
		HomeMaxMiscount	:UINT;	
		HomePosition	:BOOL;	
		OutPosition	:BOOL;	
		HomeBreakPosition	:BOOL;	
		OutBreakPosition	:BOOL;	
		InFastZone	:BOOL;	
		CurrentPosition	:DINT;	
		TargetPosition	:DINT;	
		TargetRange	:INT;	
		Reset	:BOOL;	
		MotorRun	:BOOL;	
		MotorDirection	:BOOL;	
		MotorLowSpeed	:UINT;	
		MotorHighSpeed	:UINT;	
		MotorSpeed	:UINT;	
		MotorPressSpeed	:UINT;	
		MotorPressOutTime	:UINT;	
		MotorPressOutTimer	:UINT;	
		BrakeDistance	:UINT;	
		MaxRunTime	:UINT;	
		MaxRunTimer	:UINT;	
		ErrorCode	:UINT;	
		Name	:STRING[11];	
	END_STRUCT;
			HoldCheck_Type : STRUCT
		InCounter	:UINT;	
		OutCounter	:UINT;	
		Activated	:BOOL;	
		State	:INT;	
	END_STRUCT;
			MachineProcessControl_Type : STRUCT
		Id	:UINT;	
		Name	:STRING[21];	
		State	:UINT;	
		OldState	:UINT;	
		ErrorCode	:UINT;	
		Run	:BOOL;	
		ForcedStop	:BOOL;	
		ResetAlarm	:BOOL;	
		HoldObject	:HoldCheck_Type;	
		ControlFlag	:INT;	
		Simulate	:BOOL;	
		Service	:BOOL;	
	END_STRUCT;
			MachineManager_Type : STRUCT
		MachineProcessControl	:ARRAY[0..20] OF MachineProcessControl_Type;	
	END_STRUCT;
			PositionModule_Type : STRUCT
		State	:UINT;	
		Enable	:BOOL;	
		CountA	:BOOL;	
		CountB	:BOOL;	
		OldCountA	:BOOL;	
		OldCountB	:BOOL;	
		OldA_Xor	:BOOL;	
		A_Xor	:BOOL;	
		B_Xor	:BOOL;	
		OldAXor	:BOOL;	
		OldBXor	:BOOL;	
		TrigCount	:SINT;	
		CurrentPosition	:DINT;	
		Reset	:BOOL;	
		Direction	:BOOL;	
		CountDirection	:BOOL;	
	END_STRUCT;
			TimerCount_Type : STRUCT
		_1_ms	:UINT;	
		_10_ms	:UINT;	
		_1_sec	:UINT;	
	END_STRUCT;
END_TYPE
