(********************************************************************
 * COPYRIGHT --  
 ********************************************************************
 * Program: Wheelie_Test
 * File: Wheelie_TestInit.st
 * Author: pmu
 * Created: May 01, 2013
 ********************************************************************
 * Implementation of program Wheelie_Test
 ********************************************************************)

PROGRAM _INIT


(* TODO : Add your code here *)


END_PROGRAM

