(********************************************************************
 * COPYRIGHT --  
 ********************************************************************
 * Program: XtremeHeavy
 * File: XtremeHeavyInit.st
 * Author: munchp
 * Created: September 28, 2015
 ********************************************************************
 * Implementation of program XtremeHeavy
 ********************************************************************)

PROGRAM _INIT


(* TODO : Add your code here *)


END_PROGRAM

