(********************************************************************
 * COPYRIGHT -- Microsoft
 ********************************************************************
 * Program: FactorySetting
 * File: FactorySettingInit.st
 * Author: jsstefly
 * Created: June 01, 2011
 ********************************************************************
 * Implementation of program FactorySetting
 ********************************************************************)

PROGRAM _INIT

g_OptionsAndConfigInit := FALSE;

END_PROGRAM

