(********************************************************************
 * COPYRIGHT -- IXP Data
 ********************************************************************
 * Program: Simulation
 * File: SimulationInit.st
 * Author: mazin.khalafalla
 * Created: May 27, 2019
 ********************************************************************
 * Implementation of program Simulation
 ********************************************************************)

PROGRAM _INIT



END_PROGRAM

